**** PROPERTIES SKAFFOLDER ****
{
    "forEachObj": "oneTime",
    "_partials": []
}
**** END PROPERTIES SKAFFOLDER ****
# Create image based on the official Skaffolder Xamarin image from dockerhub
FROM skaffolder/xamarin-base
